// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20230331165350_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "Dog",
                            Color = "Brownish Mix",
                            Gender = "Male",
                            Name = "Sammy"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            Breed = "Cat",
                            Color = "Blone",
                            Gender = "Female",
                            Name = "Turner"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 6,
                            Breed = "Cat",
                            Color = "Black",
                            Gender = "Female",
                            Name = "Princess"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 4,
                            Breed = "Dog",
                            Color = "White",
                            Gender = "Male",
                            Name = "George"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 7,
                            Breed = "Dog",
                            Color = "Brown",
                            Gender = "Female",
                            Name = "Epic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
